### ISSUE TITLE
Problems with hammer coral

### ISSUE THREAD

**Issue by enriarts** [Simplexity-Development/Tropica#1]
Dead hammer coral blocks which appear after a fresh coral block's death will release water when broken.

Hammer coral fans will have a proper render of their hitbox when placed on walls but won't have the right model. You also can't place hammer coral fans on the floor.

Furthermore, hammer corals have a completely off hitbox. Whereas such hitbox should extend in height to about 15 pixels, it's only 4 pixels tall (width and depth proportions are okay, though).

**Comment by RhythmicSys** [comment]
Added to #2 - I'll keep this as a running thread to post known issues onto
